feat(product): ✨ add product request validation
zinuu4/Severyanochka pull request #11
Opened 2023-09-06 16:37 UTC by velenyx

Добавил валидацию входящих значений для всех роутов продукта

2023-09-06 19:14 UTC, Iki-oops requested changes
нужно немного изменить схемы для моделей

2023-09-06 20:41 UTC, velenyx commented on server/src/models/product.model.js
> +      unique: true,
мы РК не будем делать так как он вообще не информативный и более системного характера, вместо этого будем юзать article

2023-09-06 20:48 UTC, velenyx commented on server/src/models/product.model.js
> +      unique: true,
Объяснил в TG

2023-09-08 18:35 UTC, zinuu4 approved these changes
Well done!👍🏻

2023-09-09 11:29 UTC, Iki-oops approved these changes

2023-09-09 21:39 UTC, merged