👷 ci(client): add CI for client - install, build, lint(TS|SCSS)
zinuu4/Severyanochka pull request #14
Opened 2023-09-06 17:22 UTC by velenyx

Добавил так же GitHub Actions для клиента где будут прогоняться линт ТС, стилей, установка зависимостей и сборка от Next.JS.
Так же будут запускаться при пуше и пулл реквестах на ветки main | develop.
Чтоб заработало нужно довезти до main ветки

2023-09-06 19:02 UTC, zinuu4 requested changes

2023-09-06 19:02 UTC, zinuu4 commented on .github/workflows/client.yml
I would also add jest tests here

2023-09-06 20:38 UTC, velenyx commented on .github/workflows/client.yml
Сейчас нету команды для запуска тестов, как только появится сделаю новый PR и добавлю

2023-09-07 08:47 UTC, zinuu4 approved these changes

2023-09-07 13:23 UTC, merged