✨ feat(banner): hero banner of home page
zinuu4/Severyanochka pull request #33
Opened 2023-09-21 15:07 UTC by NurkenInc

### **Feature description**
**[FRONT-END]**
    - [Banner]: Added hero banner to home page
    - [Recources]: Added necessary recources(images) for banner

2023-09-21 17:12 UTC, velenyx requested changes
Полностью поменять способ реализации. Нужен в shared Promotion

2023-09-22 02:10 UTC, Iki-oops approved these changes

2023-09-22 02:10 UTC, Iki-oops commented on client/src/page-s/home/ui/hero-banner/ui.tsx
> +import React from 'react';
Зачем здесь импорт реакта?

2023-09-22 02:10 UTC, Iki-oops commented on client/src/page-s/home/ui/home.tsx
> +import React from 'react';
ну и тут тоже

2023-09-22 14:50 UTC, velenyx requested changes

2023-09-22 14:50 UTC, velenyx commented on client/public/fruit-colored-pattern.png
я думаю будет лучше добавить доп папку - banners

2023-09-22 14:50 UTC, velenyx commented on client/src/page-s/home/ui/hero-banner/styles.module.scss
> +  background-image: url('/fruit-colored-pattern.png');
вот этот хардкод баннера хзхз

2023-09-22 14:50 UTC, velenyx commented on client/src/page-s/home/ui/hero-banner/ui.tsx
> +        src="/vegetables-card-banner.png"
и тут тоже наверное мб в какой-то конфиг вынести

2023-09-22 15:04 UTC, velenyx requested changes

2023-09-22 15:04 UTC, velenyx commented on client/src/shared/ui/promotion-card/styles.module.scss
> +.promotionCard {
Нету ховера

2023-09-22 18:23 UTC, velenyx approved these changes

2023-09-23 09:37 UTC, merged